version: '3'
services:
  licode:
    restart: 'always'
    environment:
      - MIN_PORT=30000
      - MAX_PORT=30050
      - PUBLIC_IP=chatter.stanfordssi.org
    ports:
      - "3000:3000"
      - "30000-30050:30000-30050/udp"
      - "3001:3001"
      - "8080:8080"